
/*
 * This file was automatically generated by 'scripts/Endianity'. Do no edit!
 */

#ifndef _TW_ENDIANITY_H
#define _TW_ENDIANITY_H

#define TW_PAGE_SIZE        4096

#define TW_BYTE_ORDER       1234
#define TW_LITTLE_ENDIAN    1234
#define TW_BIG_ENDIAN       4321

#endif /* _TW_ENDIANITY_H */
